# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CTMediatorTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'CTMediator'

  target 'CTMediatorTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CTMediatorTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
