# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYF_LingyiModuleCategory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'CTMediator'

  target 'ZYF_LingyiModuleCategoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYF_LingyiModuleCategoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
